// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: weather_monitor

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_panelHeaderScreen2;
extern lv_obj_t * ui_lblProjectNameMainScreen2;
extern lv_obj_t * ui_panelSensor1;
extern lv_obj_t * ui_arcSensor1;
extern lv_obj_t * ui_lblMinSensor1;
extern lv_obj_t * ui_lblMaxSensor2;
extern lv_obj_t * ui_panelBgSensor1;
extern lv_obj_t * ui_panelNumBgSensor1;
extern lv_obj_t * ui_lblSensor1;
extern lv_obj_t * ui_lblTemperature;
extern lv_obj_t * ui_panelSensor2;
extern lv_obj_t * ui_arcSensor2;
extern lv_obj_t * ui_lblMinSensor2;
extern lv_obj_t * ui_lblMaxSensor1;
extern lv_obj_t * ui_panelBgSensor2;
extern lv_obj_t * ui_panelNumBgSensor2;
extern lv_obj_t * ui_lblSensor2;
extern lv_obj_t * ui_lblHumidity;
extern lv_obj_t * ui_imgWiFiStatus2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

