// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: weather_monitor_cfg_wifi

#include "../ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_panelHeaderScreen2 = NULL;
lv_obj_t * ui_lblProjectNameMainScreen2 = NULL;
lv_obj_t * ui_imgSetting2 = NULL;
lv_obj_t * ui_panelSensor1 = NULL;
lv_obj_t * ui_arcSensor1 = NULL;
lv_obj_t * ui_lblMinSensor1 = NULL;
lv_obj_t * ui_lblMaxSensor2 = NULL;
lv_obj_t * ui_panelBgSensor1 = NULL;
lv_obj_t * ui_panelNumBgSensor1 = NULL;
lv_obj_t * ui_lblSensor1 = NULL;
lv_obj_t * ui_lblTemperature = NULL;
lv_obj_t * ui_panelSensor2 = NULL;
lv_obj_t * ui_arcSensor2 = NULL;
lv_obj_t * ui_lblMinSensor2 = NULL;
lv_obj_t * ui_lblMaxSensor1 = NULL;
lv_obj_t * ui_panelBgSensor2 = NULL;
lv_obj_t * ui_panelNumBgSensor2 = NULL;
lv_obj_t * ui_lblSensor2 = NULL;
lv_obj_t * ui_lblHumidity = NULL;
lv_obj_t * ui_imgWiFiStatus2 = NULL;
// event funtions

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0x464B55), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Screen2, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Screen2, lv_color_hex(0x414852), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panelHeaderScreen2 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_panelHeaderScreen2, lv_pct(100));
    lv_obj_set_height(ui_panelHeaderScreen2, lv_pct(10));
    lv_obj_set_align(ui_panelHeaderScreen2, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_panelHeaderScreen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_panelHeaderScreen2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_panelHeaderScreen2, lv_color_hex(0x14191E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panelHeaderScreen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_panelHeaderScreen2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblProjectNameMainScreen2 = lv_label_create(ui_panelHeaderScreen2);
    lv_obj_set_width(ui_lblProjectNameMainScreen2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblProjectNameMainScreen2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblProjectNameMainScreen2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblProjectNameMainScreen2, "Weather Monitoring Station");
    lv_obj_set_style_text_color(ui_lblProjectNameMainScreen2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblProjectNameMainScreen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblProjectNameMainScreen2, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgSetting2 = lv_image_create(ui_panelHeaderScreen2);
    lv_image_set_src(ui_imgSetting2, &ui_img_setting_50px_png);
    lv_obj_set_width(ui_imgSetting2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgSetting2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_imgSetting2, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_imgSetting2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgSetting2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_panelSensor1 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_panelSensor1, 500);
    lv_obj_set_height(ui_panelSensor1, 500);
    lv_obj_set_x(ui_panelSensor1, -250);
    lv_obj_set_y(ui_panelSensor1, 20);
    lv_obj_set_align(ui_panelSensor1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_panelSensor1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_panelSensor1, lv_color_hex(0x414852), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panelSensor1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panelSensor1, lv_color_hex(0x414852), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panelSensor1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_panelSensor1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_arcSensor1 = lv_arc_create(ui_panelSensor1);
    lv_obj_set_width(ui_arcSensor1, 420);
    lv_obj_set_height(ui_arcSensor1, 420);
    lv_obj_set_align(ui_arcSensor1, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_arcSensor1, 5, 60);
    lv_arc_set_value(ui_arcSensor1, 50);
    lv_obj_set_style_radius(ui_arcSensor1, 450, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_arcSensor1, lv_color_hex(0x1E232D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arcSensor1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_arcSensor1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_arcSensor1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_arcSensor1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_arcSensor1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_arcSensor1, lv_color_hex(0x0F1215), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arcSensor1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arcSensor1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_arcSensor1, lv_color_hex(0xF63653), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arcSensor1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arcSensor1, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_lblMinSensor1 = lv_label_create(ui_arcSensor1);
    lv_obj_set_width(ui_lblMinSensor1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblMinSensor1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblMinSensor1, 70);
    lv_obj_set_y(ui_lblMinSensor1, -25);
    lv_obj_set_align(ui_lblMinSensor1, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_lblMinSensor1, "5°C");
    lv_obj_set_style_text_color(ui_lblMinSensor1, lv_color_hex(0x36B9F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblMinSensor1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblMinSensor1, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblMaxSensor2 = lv_label_create(ui_arcSensor1);
    lv_obj_set_width(ui_lblMaxSensor2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblMaxSensor2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblMaxSensor2, -40);
    lv_obj_set_y(ui_lblMaxSensor2, -25);
    lv_obj_set_align(ui_lblMaxSensor2, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_lblMaxSensor2, "60°C");
    lv_obj_set_style_text_color(ui_lblMaxSensor2, lv_color_hex(0x36B9F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblMaxSensor2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblMaxSensor2, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panelBgSensor1 = lv_obj_create(ui_panelSensor1);
    lv_obj_set_width(ui_panelBgSensor1, 340);
    lv_obj_set_height(ui_panelBgSensor1, 340);
    lv_obj_set_align(ui_panelBgSensor1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_panelBgSensor1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_panelBgSensor1, 340, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_panelBgSensor1, lv_color_hex(0x646464), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panelBgSensor1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_panelBgSensor1, lv_color_hex(0x3C414B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_panelBgSensor1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panelBgSensor1, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panelBgSensor1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_panelBgSensor1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panelNumBgSensor1 = lv_obj_create(ui_panelBgSensor1);
    lv_obj_set_width(ui_panelNumBgSensor1, 250);
    lv_obj_set_height(ui_panelNumBgSensor1, 250);
    lv_obj_set_align(ui_panelNumBgSensor1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_panelNumBgSensor1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_panelNumBgSensor1, 250, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_panelNumBgSensor1, lv_color_hex(0x0C191E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panelNumBgSensor1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_panelNumBgSensor1, lv_color_hex(0x191C26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_panelNumBgSensor1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panelNumBgSensor1, lv_color_hex(0x5A646E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panelNumBgSensor1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblSensor1 = lv_label_create(ui_panelNumBgSensor1);
    lv_obj_set_width(ui_lblSensor1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSensor1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblSensor1, 15);
    lv_obj_set_y(ui_lblSensor1, 0);
    lv_obj_set_align(ui_lblSensor1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblSensor1, "15°");
    lv_obj_set_style_text_color(ui_lblSensor1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblSensor1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblSensor1, &ui_font_Number120, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblTemperature = lv_label_create(ui_panelSensor1);
    lv_obj_set_width(ui_lblTemperature, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblTemperature, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblTemperature, 0);
    lv_obj_set_y(ui_lblTemperature, 20);
    lv_obj_set_align(ui_lblTemperature, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_lblTemperature, "Temperature");
    lv_obj_set_style_text_color(ui_lblTemperature, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblTemperature, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblTemperature, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panelSensor2 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_panelSensor2, 500);
    lv_obj_set_height(ui_panelSensor2, 500);
    lv_obj_set_x(ui_panelSensor2, 250);
    lv_obj_set_y(ui_panelSensor2, 20);
    lv_obj_set_align(ui_panelSensor2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_panelSensor2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_panelSensor2, lv_color_hex(0x414852), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panelSensor2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panelSensor2, lv_color_hex(0x414852), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panelSensor2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_panelSensor2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_arcSensor2 = lv_arc_create(ui_panelSensor2);
    lv_obj_set_width(ui_arcSensor2, 420);
    lv_obj_set_height(ui_arcSensor2, 420);
    lv_obj_set_align(ui_arcSensor2, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_arcSensor2, 60);
    lv_obj_set_style_radius(ui_arcSensor2, 450, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_arcSensor2, lv_color_hex(0x1E232D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_arcSensor2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_arcSensor2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_arcSensor2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_arcSensor2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_arcSensor2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_arcSensor2, lv_color_hex(0x0F1215), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arcSensor2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arcSensor2, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_arcSensor2, lv_color_hex(0xF63653), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_arcSensor2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_arcSensor2, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_lblMinSensor2 = lv_label_create(ui_arcSensor2);
    lv_obj_set_width(ui_lblMinSensor2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblMinSensor2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblMinSensor2, 70);
    lv_obj_set_y(ui_lblMinSensor2, -25);
    lv_obj_set_align(ui_lblMinSensor2, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_lblMinSensor2, "0%");
    lv_obj_set_style_text_color(ui_lblMinSensor2, lv_color_hex(0x36B9F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblMinSensor2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblMinSensor2, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblMaxSensor1 = lv_label_create(ui_arcSensor2);
    lv_obj_set_width(ui_lblMaxSensor1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblMaxSensor1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblMaxSensor1, -40);
    lv_obj_set_y(ui_lblMaxSensor1, -25);
    lv_obj_set_align(ui_lblMaxSensor1, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_lblMaxSensor1, "100%");
    lv_obj_set_style_text_color(ui_lblMaxSensor1, lv_color_hex(0x36B9F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblMaxSensor1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblMaxSensor1, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panelBgSensor2 = lv_obj_create(ui_panelSensor2);
    lv_obj_set_width(ui_panelBgSensor2, 340);
    lv_obj_set_height(ui_panelBgSensor2, 340);
    lv_obj_set_align(ui_panelBgSensor2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_panelBgSensor2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_panelBgSensor2, 340, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_panelBgSensor2, lv_color_hex(0x646464), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panelBgSensor2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_panelBgSensor2, lv_color_hex(0x3C414B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_panelBgSensor2, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panelBgSensor2, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panelBgSensor2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_panelBgSensor2, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_panelNumBgSensor2 = lv_obj_create(ui_panelBgSensor2);
    lv_obj_set_width(ui_panelNumBgSensor2, 250);
    lv_obj_set_height(ui_panelNumBgSensor2, 250);
    lv_obj_set_align(ui_panelNumBgSensor2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_panelNumBgSensor2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_panelNumBgSensor2, 250, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_panelNumBgSensor2, lv_color_hex(0x0C191E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panelNumBgSensor2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_panelNumBgSensor2, lv_color_hex(0x191C26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_panelNumBgSensor2, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_panelNumBgSensor2, lv_color_hex(0x5A646E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_panelNumBgSensor2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblSensor2 = lv_label_create(ui_panelNumBgSensor2);
    lv_obj_set_width(ui_lblSensor2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblSensor2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblSensor2, 15);
    lv_obj_set_y(ui_lblSensor2, 0);
    lv_obj_set_align(ui_lblSensor2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblSensor2, "60%");
    lv_obj_set_style_text_color(ui_lblSensor2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblSensor2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblSensor2, &ui_font_Number120, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblHumidity = lv_label_create(ui_panelSensor2);
    lv_obj_set_width(ui_lblHumidity, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblHumidity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblHumidity, 0);
    lv_obj_set_y(ui_lblHumidity, 20);
    lv_obj_set_align(ui_lblHumidity, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_lblHumidity, "Humidity");
    lv_obj_set_style_text_color(ui_lblHumidity, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblHumidity, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblHumidity, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgWiFiStatus2 = lv_image_create(ui_Screen2);
    lv_image_set_src(ui_imgWiFiStatus2, &ui_img_wifi_connected_png);
    lv_obj_set_width(ui_imgWiFiStatus2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgWiFiStatus2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imgWiFiStatus2, -10);
    lv_obj_set_y(ui_imgWiFiStatus2, -10);
    lv_obj_set_align(ui_imgWiFiStatus2, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_imgWiFiStatus2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgWiFiStatus2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_panelHeaderScreen2 = NULL;
    ui_lblProjectNameMainScreen2 = NULL;
    ui_imgSetting2 = NULL;
    ui_panelSensor1 = NULL;
    ui_arcSensor1 = NULL;
    ui_lblMinSensor1 = NULL;
    ui_lblMaxSensor2 = NULL;
    ui_panelBgSensor1 = NULL;
    ui_panelNumBgSensor1 = NULL;
    ui_lblSensor1 = NULL;
    ui_lblTemperature = NULL;
    ui_panelSensor2 = NULL;
    ui_arcSensor2 = NULL;
    ui_lblMinSensor2 = NULL;
    ui_lblMaxSensor1 = NULL;
    ui_panelBgSensor2 = NULL;
    ui_panelNumBgSensor2 = NULL;
    ui_lblSensor2 = NULL;
    ui_lblHumidity = NULL;
    ui_imgWiFiStatus2 = NULL;

}
