// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: hello_world_sl

#include "../ui.h"

lv_obj_t * ui_MainScreen = NULL;
lv_obj_t * ui_lblHelloWorld = NULL;
// event funtions

// build funtions

void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblHelloWorld = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_lblHelloWorld, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblHelloWorld, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblHelloWorld, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblHelloWorld, "Hello World");

}

void ui_MainScreen_screen_destroy(void)
{
    if(ui_MainScreen) lv_obj_del(ui_MainScreen);

    // NULL screen variables
    ui_MainScreen = NULL;
    ui_lblHelloWorld = NULL;

}
