// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: hello_world_sl

#include "../ui.h"

lv_obj_t * ui_MainScreen = NULL;
lv_obj_t * ui_imgLogo = NULL;
lv_obj_t * ui_lblHelloWorld = NULL;
// event funtions

// build funtions

void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgLogo = lv_image_create(ui_MainScreen);
    lv_image_set_src(ui_imgLogo, &ui_img_logo2_png);
    lv_obj_set_width(ui_imgLogo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgLogo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_imgLogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgLogo, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgLogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_lblHelloWorld = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_lblHelloWorld, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblHelloWorld, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblHelloWorld, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblHelloWorld, "Hello World using Square Line Studio");
    lv_obj_set_style_text_font(ui_lblHelloWorld, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_MainScreen_screen_destroy(void)
{
    if(ui_MainScreen) lv_obj_del(ui_MainScreen);

    // NULL screen variables
    ui_MainScreen = NULL;
    ui_imgLogo = NULL;
    ui_lblHelloWorld = NULL;

}
