// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: hello_world_sl

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_imgLogo = NULL;
lv_obj_t * ui_panelHeaderScreen1 = NULL;
lv_obj_t * ui_lblProjectNameMainScreen1 = NULL;
lv_obj_t * ui_imgWiFiStatus1 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgLogo = lv_image_create(ui_Screen1);
    lv_obj_set_width(ui_imgLogo, lv_pct(100));
    lv_obj_set_height(ui_imgLogo, lv_pct(100));
    lv_obj_set_align(ui_imgLogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgLogo, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgLogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_panelHeaderScreen1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_panelHeaderScreen1, lv_pct(100));
    lv_obj_set_height(ui_panelHeaderScreen1, lv_pct(10));
    lv_obj_set_align(ui_panelHeaderScreen1, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_panelHeaderScreen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_panelHeaderScreen1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_panelHeaderScreen1, lv_color_hex(0x14191E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_panelHeaderScreen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_panelHeaderScreen1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblProjectNameMainScreen1 = lv_label_create(ui_panelHeaderScreen1);
    lv_obj_set_width(ui_lblProjectNameMainScreen1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblProjectNameMainScreen1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_lblProjectNameMainScreen1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblProjectNameMainScreen1, "Weather Monitoring Station");
    lv_obj_set_style_text_color(ui_lblProjectNameMainScreen1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblProjectNameMainScreen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblProjectNameMainScreen1, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgWiFiStatus1 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_imgWiFiStatus1, &ui_img_wifi_disconnected_png);
    lv_obj_set_width(ui_imgWiFiStatus1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imgWiFiStatus1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imgWiFiStatus1, -10);
    lv_obj_set_y(ui_imgWiFiStatus1, -10);
    lv_obj_set_align(ui_imgWiFiStatus1, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_imgWiFiStatus1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgWiFiStatus1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_imgLogo = NULL;
    ui_panelHeaderScreen1 = NULL;
    ui_lblProjectNameMainScreen1 = NULL;
    ui_imgWiFiStatus1 = NULL;

}
