// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: weather_monitor_cfg_wifi

#ifndef _WEATHER_MONITOR_CFG_WIFI_UI_H
#define _WEATHER_MONITOR_CFG_WIFI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen1.h"
#include "screens/ui_Screen2.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_setting_50px_png);    // assets/setting_50px.png
LV_IMG_DECLARE(ui_img_wifi_disconnected_png);    // assets/wifi_disconnected.png
LV_IMG_DECLARE(ui_img_wifi_connected_png);    // assets/wifi_connected.png
LV_IMG_DECLARE(ui_img_logo1_png);    // assets/logo1.png
LV_IMG_DECLARE(ui_img_logo2_png);    // assets/logo2.png
LV_IMG_DECLARE(ui_img_logo3_png);    // assets/logo3.png
LV_IMG_DECLARE(ui_img_wifi_png);    // assets/wifi.png
LV_IMG_DECLARE(ui_img_setting_100px_png);    // assets/setting_100px.png

// FONTS
LV_FONT_DECLARE(ui_font_Number120);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
